/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.tables.daos;


import com.stefandragomiroiu.rideshare.jooq.AbstractSpringDAOImpl;
import com.stefandragomiroiu.rideshare.jooq.tables.BookingConnection;
import com.stefandragomiroiu.rideshare.jooq.tables.records.BookingConnectionRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class BookingConnectionDao extends AbstractSpringDAOImpl<BookingConnectionRecord, com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection, Record2<Long, Long>> {

    /**
     * Create a new BookingConnectionDao without any configuration
     */
    public BookingConnectionDao() {
        super(BookingConnection.BOOKING_CONNECTION, com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection.class);
    }

    /**
     * Create a new BookingConnectionDao with an attached configuration
     */
    @Autowired
    public BookingConnectionDao(Configuration configuration) {
        super(BookingConnection.BOOKING_CONNECTION, com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection object) {
        return compositeKeyRecord(object.getBookingId(), object.getConnectionId());
    }

    /**
     * Fetch records that have <code>booking_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection> fetchRangeOfBookingId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BookingConnection.BOOKING_CONNECTION.BOOKING_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>booking_id IN (values)</code>
     */
    public List<com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection> fetchByBookingId(Long... values) {
        return fetch(BookingConnection.BOOKING_CONNECTION.BOOKING_ID, values);
    }

    /**
     * Fetch records that have <code>connection_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection> fetchRangeOfConnectionId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BookingConnection.BOOKING_CONNECTION.CONNECTION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>connection_id IN (values)</code>
     */
    public List<com.stefandragomiroiu.rideshare.jooq.tables.pojos.BookingConnection> fetchByConnectionId(Long... values) {
        return fetch(BookingConnection.BOOKING_CONNECTION.CONNECTION_ID, values);
    }
}
