### Find all
GET {{host}}/locations

### Find by id
GET {{host}}/locations/2

### Create
POST {{host}}/locations
Content-Type: application/json

{
  "city": "Draga",
  "county": "VL"
}

### Update
PUT {{host}}/locations/1
Content-Type: application/json

{
  "locationId": 1,
  "city": "Dragasani",
  "county": "VL"
}

### Delete
DELETE {{host}}/locations/1
