### Find all
GET {{host}}/locations

###  Find by City Containing
GET {{host}}/locations/findByCityContaining?city=dra

### Find by id
GET {{host}}/locations/2

### Create
POST {{host}}/locations
Content-Type: application/json

{
  "city": "Draga6",
  "county": "VL"
}

### Update
PUT {{host}}/locations/5
Content-Type: application/json

{
  "locationId": 5,
  "city": "Draga 5",
  "county": "VL"
}

### Delete
DELETE {{host}}/locations/1
