/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq;


import com.stefandragomiroiu.rideshare.jooq.tables.Booking;
import com.stefandragomiroiu.rideshare.jooq.tables.BookingConnection;
import com.stefandragomiroiu.rideshare.jooq.tables.Location;
import com.stefandragomiroiu.rideshare.jooq.tables.Ride;
import com.stefandragomiroiu.rideshare.jooq.tables.RideConnection;
import com.stefandragomiroiu.rideshare.jooq.tables.RideRating;
import com.stefandragomiroiu.rideshare.jooq.tables.User;
import com.stefandragomiroiu.rideshare.jooq.tables.Vehicle;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.booking</code>.
     */
    public final Booking BOOKING = Booking.BOOKING;

    /**
     * The table <code>public.booking_connection</code>.
     */
    public final BookingConnection BOOKING_CONNECTION = BookingConnection.BOOKING_CONNECTION;

    /**
     * The table <code>public.location</code>.
     */
    public final Location LOCATION = Location.LOCATION;

    /**
     * The table <code>public.ride</code>.
     */
    public final Ride RIDE = Ride.RIDE;

    /**
     * The table <code>public.ride_connection</code>.
     */
    public final RideConnection RIDE_CONNECTION = RideConnection.RIDE_CONNECTION;

    /**
     * The table <code>public.ride_rating</code>.
     */
    public final RideRating RIDE_RATING = RideRating.RIDE_RATING;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.vehicle</code>.
     */
    public final Vehicle VEHICLE = Vehicle.VEHICLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Booking.BOOKING,
            BookingConnection.BOOKING_CONNECTION,
            Location.LOCATION,
            Ride.RIDE,
            RideConnection.RIDE_CONNECTION,
            RideRating.RIDE_RATING,
            User.USER,
            Vehicle.VEHICLE
        );
    }
}
