/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq;


import com.stefandragomiroiu.rideshare.jooq.tables.Booking;
import com.stefandragomiroiu.rideshare.jooq.tables.BookingConnection;
import com.stefandragomiroiu.rideshare.jooq.tables.Location;
import com.stefandragomiroiu.rideshare.jooq.tables.Ride;
import com.stefandragomiroiu.rideshare.jooq.tables.RideConnection;
import com.stefandragomiroiu.rideshare.jooq.tables.RideRating;
import com.stefandragomiroiu.rideshare.jooq.tables.User;
import com.stefandragomiroiu.rideshare.jooq.tables.Vehicle;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.booking</code>.
     */
    public static final Booking BOOKING = Booking.BOOKING;

    /**
     * The table <code>public.booking_connection</code>.
     */
    public static final BookingConnection BOOKING_CONNECTION = BookingConnection.BOOKING_CONNECTION;

    /**
     * The table <code>public.location</code>.
     */
    public static final Location LOCATION = Location.LOCATION;

    /**
     * The table <code>public.ride</code>.
     */
    public static final Ride RIDE = Ride.RIDE;

    /**
     * The table <code>public.ride_connection</code>.
     */
    public static final RideConnection RIDE_CONNECTION = RideConnection.RIDE_CONNECTION;

    /**
     * The table <code>public.ride_rating</code>.
     */
    public static final RideRating RIDE_RATING = RideRating.RIDE_RATING;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.vehicle</code>.
     */
    public static final Vehicle VEHICLE = Vehicle.VEHICLE;
}
