/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.enums;


import com.stefandragomiroiu.rideshare.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum RideStatus implements EnumType {

    ACTIVE("ACTIVE"),

    FINISHED("FINISHED"),

    CANCELED("CANCELED");

    private final String literal;

    private RideStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "ride_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static RideStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(RideStatus.class, literal);
    }
}
