/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Booking implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long bookingId;
    private Long userId;
    private Integer adults;
    private Integer children;
    private Boolean confirmed;
    private LocalDateTime bookedAt;

    public Booking() {}

    public Booking(Booking value) {
        this.bookingId = value.bookingId;
        this.userId = value.userId;
        this.adults = value.adults;
        this.children = value.children;
        this.confirmed = value.confirmed;
        this.bookedAt = value.bookedAt;
    }

    public Booking(
        Long bookingId,
        Long userId,
        Integer adults,
        Integer children,
        Boolean confirmed,
        LocalDateTime bookedAt
    ) {
        this.bookingId = bookingId;
        this.userId = userId;
        this.adults = adults;
        this.children = children;
        this.confirmed = confirmed;
        this.bookedAt = bookedAt;
    }

    /**
     * Getter for <code>public.booking.booking_id</code>.
     */
    public Long getBookingId() {
        return this.bookingId;
    }

    /**
     * Setter for <code>public.booking.booking_id</code>.
     */
    public void setBookingId(Long bookingId) {
        this.bookingId = bookingId;
    }

    /**
     * Getter for <code>public.booking.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.booking.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.booking.adults</code>.
     */
    public Integer getAdults() {
        return this.adults;
    }

    /**
     * Setter for <code>public.booking.adults</code>.
     */
    public void setAdults(Integer adults) {
        this.adults = adults;
    }

    /**
     * Getter for <code>public.booking.children</code>.
     */
    public Integer getChildren() {
        return this.children;
    }

    /**
     * Setter for <code>public.booking.children</code>.
     */
    public void setChildren(Integer children) {
        this.children = children;
    }

    /**
     * Getter for <code>public.booking.confirmed</code>.
     */
    public Boolean getConfirmed() {
        return this.confirmed;
    }

    /**
     * Setter for <code>public.booking.confirmed</code>.
     */
    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    /**
     * Getter for <code>public.booking.booked_at</code>.
     */
    public LocalDateTime getBookedAt() {
        return this.bookedAt;
    }

    /**
     * Setter for <code>public.booking.booked_at</code>.
     */
    public void setBookedAt(LocalDateTime bookedAt) {
        this.bookedAt = bookedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Booking other = (Booking) obj;
        if (this.bookingId == null) {
            if (other.bookingId != null)
                return false;
        }
        else if (!this.bookingId.equals(other.bookingId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.adults == null) {
            if (other.adults != null)
                return false;
        }
        else if (!this.adults.equals(other.adults))
            return false;
        if (this.children == null) {
            if (other.children != null)
                return false;
        }
        else if (!this.children.equals(other.children))
            return false;
        if (this.confirmed == null) {
            if (other.confirmed != null)
                return false;
        }
        else if (!this.confirmed.equals(other.confirmed))
            return false;
        if (this.bookedAt == null) {
            if (other.bookedAt != null)
                return false;
        }
        else if (!this.bookedAt.equals(other.bookedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.bookingId == null) ? 0 : this.bookingId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.adults == null) ? 0 : this.adults.hashCode());
        result = prime * result + ((this.children == null) ? 0 : this.children.hashCode());
        result = prime * result + ((this.confirmed == null) ? 0 : this.confirmed.hashCode());
        result = prime * result + ((this.bookedAt == null) ? 0 : this.bookedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Booking (");

        sb.append(bookingId);
        sb.append(", ").append(userId);
        sb.append(", ").append(adults);
        sb.append(", ").append(children);
        sb.append(", ").append(confirmed);
        sb.append(", ").append(bookedAt);

        sb.append(")");
        return sb.toString();
    }
}
