/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Location implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long locationId;
    private String city;
    private String county;

    public Location() {}

    public Location(Location value) {
        this.locationId = value.locationId;
        this.city = value.city;
        this.county = value.county;
    }

    public Location(
        Long locationId,
        String city,
        String county
    ) {
        this.locationId = locationId;
        this.city = city;
        this.county = county;
    }

    /**
     * Getter for <code>public.location.location_id</code>.
     */
    public Long getLocationId() {
        return this.locationId;
    }

    /**
     * Setter for <code>public.location.location_id</code>.
     */
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for <code>public.location.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.location.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>public.location.county</code>.
     */
    public String getCounty() {
        return this.county;
    }

    /**
     * Setter for <code>public.location.county</code>.
     */
    public void setCounty(String county) {
        this.county = county;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Location other = (Location) obj;
        if (this.locationId == null) {
            if (other.locationId != null)
                return false;
        }
        else if (!this.locationId.equals(other.locationId))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.county == null) {
            if (other.county != null)
                return false;
        }
        else if (!this.county.equals(other.county))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.locationId == null) ? 0 : this.locationId.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.county == null) ? 0 : this.county.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Location (");

        sb.append(locationId);
        sb.append(", ").append(city);
        sb.append(", ").append(county);

        sb.append(")");
        return sb.toString();
    }
}
