/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.tables.pojos;


import com.stefandragomiroiu.rideshare.jooq.enums.RideStatus;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ride implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long rideId;
    private Long driver;
    private LocalDate departureDate;
    private Integer seats;
    private String additionalComment;
    private String vehicle;
    private RideStatus status;
    private LocalDateTime postedAt;

    public Ride() {}

    public Ride(Ride value) {
        this.rideId = value.rideId;
        this.driver = value.driver;
        this.departureDate = value.departureDate;
        this.seats = value.seats;
        this.additionalComment = value.additionalComment;
        this.vehicle = value.vehicle;
        this.status = value.status;
        this.postedAt = value.postedAt;
    }

    public Ride(
        Long rideId,
        Long driver,
        LocalDate departureDate,
        Integer seats,
        String additionalComment,
        String vehicle,
        RideStatus status,
        LocalDateTime postedAt
    ) {
        this.rideId = rideId;
        this.driver = driver;
        this.departureDate = departureDate;
        this.seats = seats;
        this.additionalComment = additionalComment;
        this.vehicle = vehicle;
        this.status = status;
        this.postedAt = postedAt;
    }

    /**
     * Getter for <code>public.ride.ride_id</code>.
     */
    public Long getRideId() {
        return this.rideId;
    }

    /**
     * Setter for <code>public.ride.ride_id</code>.
     */
    public void setRideId(Long rideId) {
        this.rideId = rideId;
    }

    /**
     * Getter for <code>public.ride.driver</code>.
     */
    public Long getDriver() {
        return this.driver;
    }

    /**
     * Setter for <code>public.ride.driver</code>.
     */
    public void setDriver(Long driver) {
        this.driver = driver;
    }

    /**
     * Getter for <code>public.ride.departure_date</code>.
     */
    public LocalDate getDepartureDate() {
        return this.departureDate;
    }

    /**
     * Setter for <code>public.ride.departure_date</code>.
     */
    public void setDepartureDate(LocalDate departureDate) {
        this.departureDate = departureDate;
    }

    /**
     * Getter for <code>public.ride.seats</code>.
     */
    public Integer getSeats() {
        return this.seats;
    }

    /**
     * Setter for <code>public.ride.seats</code>.
     */
    public void setSeats(Integer seats) {
        this.seats = seats;
    }

    /**
     * Getter for <code>public.ride.additional_comment</code>.
     */
    public String getAdditionalComment() {
        return this.additionalComment;
    }

    /**
     * Setter for <code>public.ride.additional_comment</code>.
     */
    public void setAdditionalComment(String additionalComment) {
        this.additionalComment = additionalComment;
    }

    /**
     * Getter for <code>public.ride.vehicle</code>.
     */
    public String getVehicle() {
        return this.vehicle;
    }

    /**
     * Setter for <code>public.ride.vehicle</code>.
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * Getter for <code>public.ride.status</code>.
     */
    public RideStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.ride.status</code>.
     */
    public void setStatus(RideStatus status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.ride.posted_at</code>.
     */
    public LocalDateTime getPostedAt() {
        return this.postedAt;
    }

    /**
     * Setter for <code>public.ride.posted_at</code>.
     */
    public void setPostedAt(LocalDateTime postedAt) {
        this.postedAt = postedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Ride other = (Ride) obj;
        if (this.rideId == null) {
            if (other.rideId != null)
                return false;
        }
        else if (!this.rideId.equals(other.rideId))
            return false;
        if (this.driver == null) {
            if (other.driver != null)
                return false;
        }
        else if (!this.driver.equals(other.driver))
            return false;
        if (this.departureDate == null) {
            if (other.departureDate != null)
                return false;
        }
        else if (!this.departureDate.equals(other.departureDate))
            return false;
        if (this.seats == null) {
            if (other.seats != null)
                return false;
        }
        else if (!this.seats.equals(other.seats))
            return false;
        if (this.additionalComment == null) {
            if (other.additionalComment != null)
                return false;
        }
        else if (!this.additionalComment.equals(other.additionalComment))
            return false;
        if (this.vehicle == null) {
            if (other.vehicle != null)
                return false;
        }
        else if (!this.vehicle.equals(other.vehicle))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.postedAt == null) {
            if (other.postedAt != null)
                return false;
        }
        else if (!this.postedAt.equals(other.postedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.rideId == null) ? 0 : this.rideId.hashCode());
        result = prime * result + ((this.driver == null) ? 0 : this.driver.hashCode());
        result = prime * result + ((this.departureDate == null) ? 0 : this.departureDate.hashCode());
        result = prime * result + ((this.seats == null) ? 0 : this.seats.hashCode());
        result = prime * result + ((this.additionalComment == null) ? 0 : this.additionalComment.hashCode());
        result = prime * result + ((this.vehicle == null) ? 0 : this.vehicle.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.postedAt == null) ? 0 : this.postedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ride (");

        sb.append(rideId);
        sb.append(", ").append(driver);
        sb.append(", ").append(departureDate);
        sb.append(", ").append(seats);
        sb.append(", ").append(additionalComment);
        sb.append(", ").append(vehicle);
        sb.append(", ").append(status);
        sb.append(", ").append(postedAt);

        sb.append(")");
        return sb.toString();
    }
}
