/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Vehicle implements Serializable {

    private static final long serialVersionUID = 1L;

    private String plateNumber;
    private String brand;
    private String model;
    private String color;
    private Integer registrationYear;
    private Integer seats;
    private Long owner;

    public Vehicle() {}

    public Vehicle(Vehicle value) {
        this.plateNumber = value.plateNumber;
        this.brand = value.brand;
        this.model = value.model;
        this.color = value.color;
        this.registrationYear = value.registrationYear;
        this.seats = value.seats;
        this.owner = value.owner;
    }

    public Vehicle(
        String plateNumber,
        String brand,
        String model,
        String color,
        Integer registrationYear,
        Integer seats,
        Long owner
    ) {
        this.plateNumber = plateNumber;
        this.brand = brand;
        this.model = model;
        this.color = color;
        this.registrationYear = registrationYear;
        this.seats = seats;
        this.owner = owner;
    }

    /**
     * Getter for <code>public.vehicle.plate_number</code>.
     */
    public String getPlateNumber() {
        return this.plateNumber;
    }

    /**
     * Setter for <code>public.vehicle.plate_number</code>.
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * Getter for <code>public.vehicle.brand</code>.
     */
    public String getBrand() {
        return this.brand;
    }

    /**
     * Setter for <code>public.vehicle.brand</code>.
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * Getter for <code>public.vehicle.model</code>.
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Setter for <code>public.vehicle.model</code>.
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Getter for <code>public.vehicle.color</code>.
     */
    public String getColor() {
        return this.color;
    }

    /**
     * Setter for <code>public.vehicle.color</code>.
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Getter for <code>public.vehicle.registration_year</code>.
     */
    public Integer getRegistrationYear() {
        return this.registrationYear;
    }

    /**
     * Setter for <code>public.vehicle.registration_year</code>.
     */
    public void setRegistrationYear(Integer registrationYear) {
        this.registrationYear = registrationYear;
    }

    /**
     * Getter for <code>public.vehicle.seats</code>.
     */
    public Integer getSeats() {
        return this.seats;
    }

    /**
     * Setter for <code>public.vehicle.seats</code>.
     */
    public void setSeats(Integer seats) {
        this.seats = seats;
    }

    /**
     * Getter for <code>public.vehicle.owner</code>.
     */
    public Long getOwner() {
        return this.owner;
    }

    /**
     * Setter for <code>public.vehicle.owner</code>.
     */
    public void setOwner(Long owner) {
        this.owner = owner;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Vehicle other = (Vehicle) obj;
        if (this.plateNumber == null) {
            if (other.plateNumber != null)
                return false;
        }
        else if (!this.plateNumber.equals(other.plateNumber))
            return false;
        if (this.brand == null) {
            if (other.brand != null)
                return false;
        }
        else if (!this.brand.equals(other.brand))
            return false;
        if (this.model == null) {
            if (other.model != null)
                return false;
        }
        else if (!this.model.equals(other.model))
            return false;
        if (this.color == null) {
            if (other.color != null)
                return false;
        }
        else if (!this.color.equals(other.color))
            return false;
        if (this.registrationYear == null) {
            if (other.registrationYear != null)
                return false;
        }
        else if (!this.registrationYear.equals(other.registrationYear))
            return false;
        if (this.seats == null) {
            if (other.seats != null)
                return false;
        }
        else if (!this.seats.equals(other.seats))
            return false;
        if (this.owner == null) {
            if (other.owner != null)
                return false;
        }
        else if (!this.owner.equals(other.owner))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.plateNumber == null) ? 0 : this.plateNumber.hashCode());
        result = prime * result + ((this.brand == null) ? 0 : this.brand.hashCode());
        result = prime * result + ((this.model == null) ? 0 : this.model.hashCode());
        result = prime * result + ((this.color == null) ? 0 : this.color.hashCode());
        result = prime * result + ((this.registrationYear == null) ? 0 : this.registrationYear.hashCode());
        result = prime * result + ((this.seats == null) ? 0 : this.seats.hashCode());
        result = prime * result + ((this.owner == null) ? 0 : this.owner.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vehicle (");

        sb.append(plateNumber);
        sb.append(", ").append(brand);
        sb.append(", ").append(model);
        sb.append(", ").append(color);
        sb.append(", ").append(registrationYear);
        sb.append(", ").append(seats);
        sb.append(", ").append(owner);

        sb.append(")");
        return sb.toString();
    }
}
