/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.tables.records;


import com.stefandragomiroiu.rideshare.jooq.enums.Role;
import com.stefandragomiroiu.rideshare.jooq.tables.User;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record11<Long, String, String, String, String, String, LocalDate, String, LocalDateTime, LocalDateTime, Role> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user.birth_date</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>public.user.profile_picture</code>.
     */
    public void setProfilePicture(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user.profile_picture</code>.
     */
    public String getProfilePicture() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.user.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.user.last_login</code>.
     */
    public void setLastLogin(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.user.role</code>.
     */
    public void setRole(Role value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.user.role</code>.
     */
    public Role getRole() {
        return (Role) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, String, String, LocalDate, String, LocalDateTime, LocalDateTime, Role> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, String, String, LocalDate, String, LocalDateTime, LocalDateTime, Role> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return User.USER.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return User.USER.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return User.USER.PHONE_NUMBER;
    }

    @Override
    public Field<LocalDate> field7() {
        return User.USER.BIRTH_DATE;
    }

    @Override
    public Field<String> field8() {
        return User.USER.PROFILE_PICTURE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return User.USER.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return User.USER.LAST_LOGIN;
    }

    @Override
    public Field<Role> field11() {
        return User.USER.ROLE;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getPhoneNumber();
    }

    @Override
    public LocalDate component7() {
        return getBirthDate();
    }

    @Override
    public String component8() {
        return getProfilePicture();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component10() {
        return getLastLogin();
    }

    @Override
    public Role component11() {
        return getRole();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getPhoneNumber();
    }

    @Override
    public LocalDate value7() {
        return getBirthDate();
    }

    @Override
    public String value8() {
        return getProfilePicture();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value10() {
        return getLastLogin();
    }

    @Override
    public Role value11() {
        return getRole();
    }

    @Override
    public UserRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public UserRecord value7(LocalDate value) {
        setBirthDate(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setProfilePicture(value);
        return this;
    }

    @Override
    public UserRecord value9(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public UserRecord value10(LocalDateTime value) {
        setLastLogin(value);
        return this;
    }

    @Override
    public UserRecord value11(Role value) {
        setRole(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, LocalDate value7, String value8, LocalDateTime value9, LocalDateTime value10, Role value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long userId, String email, String password, String firstName, String lastName, String phoneNumber, LocalDate birthDate, String profilePicture, LocalDateTime createdOn, LocalDateTime lastLogin, Role role) {
        super(User.USER);

        setUserId(userId);
        setEmail(email);
        setPassword(password);
        setFirstName(firstName);
        setLastName(lastName);
        setPhoneNumber(phoneNumber);
        setBirthDate(birthDate);
        setProfilePicture(profilePicture);
        setCreatedOn(createdOn);
        setLastLogin(lastLogin);
        setRole(role);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(com.stefandragomiroiu.rideshare.jooq.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setUserId(value.getUserId());
            setEmail(value.getEmail());
            setPassword(value.getPassword());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setPhoneNumber(value.getPhoneNumber());
            setBirthDate(value.getBirthDate());
            setProfilePicture(value.getProfilePicture());
            setCreatedOn(value.getCreatedOn());
            setLastLogin(value.getLastLogin());
            setRole(value.getRole());
            resetChangedOnNotNull();
        }
    }
}
