/*
 * This file is generated by jOOQ.
 */
package com.stefandragomiroiu.rideshare.jooq.tables.records;


import com.stefandragomiroiu.rideshare.jooq.tables.Vehicle;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VehicleRecord extends UpdatableRecordImpl<VehicleRecord> implements Record7<String, String, String, String, Integer, Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vehicle.plate_number</code>.
     */
    public void setPlateNumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vehicle.plate_number</code>.
     */
    public String getPlateNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.vehicle.brand</code>.
     */
    public void setBrand(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vehicle.brand</code>.
     */
    public String getBrand() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vehicle.model</code>.
     */
    public void setModel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vehicle.model</code>.
     */
    public String getModel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vehicle.color</code>.
     */
    public void setColor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vehicle.color</code>.
     */
    public String getColor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vehicle.registration_year</code>.
     */
    public void setRegistrationYear(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vehicle.registration_year</code>.
     */
    public Integer getRegistrationYear() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.vehicle.seats</code>.
     */
    public void setSeats(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vehicle.seats</code>.
     */
    public Integer getSeats() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.vehicle.owner</code>.
     */
    public void setOwner(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vehicle.owner</code>.
     */
    public Long getOwner() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, Integer, Integer, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, Integer, Integer, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Vehicle.VEHICLE.PLATE_NUMBER;
    }

    @Override
    public Field<String> field2() {
        return Vehicle.VEHICLE.BRAND;
    }

    @Override
    public Field<String> field3() {
        return Vehicle.VEHICLE.MODEL;
    }

    @Override
    public Field<String> field4() {
        return Vehicle.VEHICLE.COLOR;
    }

    @Override
    public Field<Integer> field5() {
        return Vehicle.VEHICLE.REGISTRATION_YEAR;
    }

    @Override
    public Field<Integer> field6() {
        return Vehicle.VEHICLE.SEATS;
    }

    @Override
    public Field<Long> field7() {
        return Vehicle.VEHICLE.OWNER;
    }

    @Override
    public String component1() {
        return getPlateNumber();
    }

    @Override
    public String component2() {
        return getBrand();
    }

    @Override
    public String component3() {
        return getModel();
    }

    @Override
    public String component4() {
        return getColor();
    }

    @Override
    public Integer component5() {
        return getRegistrationYear();
    }

    @Override
    public Integer component6() {
        return getSeats();
    }

    @Override
    public Long component7() {
        return getOwner();
    }

    @Override
    public String value1() {
        return getPlateNumber();
    }

    @Override
    public String value2() {
        return getBrand();
    }

    @Override
    public String value3() {
        return getModel();
    }

    @Override
    public String value4() {
        return getColor();
    }

    @Override
    public Integer value5() {
        return getRegistrationYear();
    }

    @Override
    public Integer value6() {
        return getSeats();
    }

    @Override
    public Long value7() {
        return getOwner();
    }

    @Override
    public VehicleRecord value1(String value) {
        setPlateNumber(value);
        return this;
    }

    @Override
    public VehicleRecord value2(String value) {
        setBrand(value);
        return this;
    }

    @Override
    public VehicleRecord value3(String value) {
        setModel(value);
        return this;
    }

    @Override
    public VehicleRecord value4(String value) {
        setColor(value);
        return this;
    }

    @Override
    public VehicleRecord value5(Integer value) {
        setRegistrationYear(value);
        return this;
    }

    @Override
    public VehicleRecord value6(Integer value) {
        setSeats(value);
        return this;
    }

    @Override
    public VehicleRecord value7(Long value) {
        setOwner(value);
        return this;
    }

    @Override
    public VehicleRecord values(String value1, String value2, String value3, String value4, Integer value5, Integer value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehicleRecord
     */
    public VehicleRecord() {
        super(Vehicle.VEHICLE);
    }

    /**
     * Create a detached, initialised VehicleRecord
     */
    public VehicleRecord(String plateNumber, String brand, String model, String color, Integer registrationYear, Integer seats, Long owner) {
        super(Vehicle.VEHICLE);

        setPlateNumber(plateNumber);
        setBrand(brand);
        setModel(model);
        setColor(color);
        setRegistrationYear(registrationYear);
        setSeats(seats);
        setOwner(owner);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VehicleRecord
     */
    public VehicleRecord(com.stefandragomiroiu.rideshare.jooq.tables.pojos.Vehicle value) {
        super(Vehicle.VEHICLE);

        if (value != null) {
            setPlateNumber(value.getPlateNumber());
            setBrand(value.getBrand());
            setModel(value.getModel());
            setColor(value.getColor());
            setRegistrationYear(value.getRegistrationYear());
            setSeats(value.getSeats());
            setOwner(value.getOwner());
            resetChangedOnNotNull();
        }
    }
}
